spring:

  application:
    name: FOOTBALL-DATA-SERVICE


  datasource:
    url: jdbc:mysql://${DB_HOST}/${DB_NAME}?useSSL=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  h2:
    console:
      enabled: true




external-services:
  football:
    base-url: https://apiv3.apifootball.com/
    api-key: ${FOOTBALL_API_KEY}

server:
  port: 8080
